// MARK: Categorise
// MARK: ChunkWindowSplit
// MARK: Combinations
// MARK: Cycle
// MARK: Enumerate
// MARK: Finding
// MARK: HopJump
// MARK: Interpose
// MARK: NestedSequences
// MARK: Permutations
// MARK: ScanReduce
// MARK: TakeDrop
// MARK: Zip